// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250606144919_SeedOffers")]
    partial class SeedOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BannerImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Casino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descryption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiberatedAmount")
                        .HasColumnType("int");

                    b.Property<int>("MaxFreeAmount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BannerImg = "codigo_bono_betfair.png",
                            Casino = "BetFair",
                            Descryption = "📈 Cuota mínima 1.5\n\n🆕 Solo está disponible para nuevos usuarios registrados en www.betfair.es con el código promocional ZBBES2\n\n⏰ Tendrás 7 días desde que te acreditemos tu apuesta gratuita para utilizarla\n\n🎯 Podrás utilizar tu apuesta gratuita en cualquier evento",
                            LiberatedAmount = 0,
                            MaxFreeAmount = 200,
                            Title = "Hasta 200€ en Apuestas Gratis",
                            Type = "Bono Bienvenida🎁"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BannerImg = "codigo_bono_bwin.png",
                            Casino = "Bwin",
                            Descryption = "🎯 Solo será válida la primera apuesta realizada después de registrarte\n\n💶 La primera apuesta tras registrarte (mínimo 1 €, saldo real, no virtuales) se devuelve al 100% (hasta 100 €) como Apuesta Gratuita si la pierdes\n\n⏳ Las Apuestas Gratuitas y Apuestas Seguras que te den tienen 7 días para usarse y solo devuelven la ganancia neta\n\n📅 Apuesta válida dentro de 30 días desde el registro, sin usar bonos ni supercuotas",
                            LiberatedAmount = 0,
                            MaxFreeAmount = 100,
                            Title = "Hasta 100€ asegurados en tu 1ª apuesta",
                            Type = "Bono Bienvenida🎁"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BannerImg = "codigo_bono_interwetten.png",
                            Casino = "Interwetten",
                            Descryption = "💰 El importe máximo para la apuesta sin riesgo es de 50 €\n\n🎯 Una apuesta de 40 € fallada otorga una apuesta gratuita de 40 €\n\n🎯 Una apuesta de 60 € fallada otorga una apuesta gratuita de 50 €\n\n🔢 El importe mínimo de apuesta debe ser de 10 €\n\n❌ Solo se tendrán en cuenta las apuestas falladas\n\n⚽ Pueden realizar apuestas simples o combinadas, live o prepartido para esta promoción",
                            LiberatedAmount = 0,
                            MaxFreeAmount = 50,
                            Title = "¡Tu primera apuesta sin riesgo hasta 50€!",
                            Type = "Bono Bienvenida🎁"
                        });
                });

            modelBuilder.Entity("API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.Entities.UserOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LiberatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOffers");
                });

            modelBuilder.Entity("Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatePlaced")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSureBet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWon")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserOfferId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("API.Models.Entities.UserOffer", b =>
                {
                    b.HasOne("API.Models.Entities.Offer", "Offer")
                        .WithMany("UserOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Entities.User", "User")
                        .WithMany("UserOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bet", b =>
                {
                    b.HasOne("API.Models.Entities.UserOffer", "UserOffer")
                        .WithMany("Bets")
                        .HasForeignKey("UserOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserOffer");
                });

            modelBuilder.Entity("API.Models.Entities.Offer", b =>
                {
                    b.Navigation("UserOffers");
                });

            modelBuilder.Entity("API.Models.Entities.User", b =>
                {
                    b.Navigation("UserOffers");
                });

            modelBuilder.Entity("API.Models.Entities.UserOffer", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
